# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68eec8ee7fb3794178fb803603aca3d7c5599e520ab2c26c3298c1720c266e4e1f03b0ea3ffabfb9497d3467430d217fc173ae5564fbc365b00e1b024eaad896

test:
  secret_key_base: 904d2a2eaab1bf33bc6c0d1428d93c5f28075477847054cf3ae87f5aa214be6c0c3e2abb34c2fc0e197f8d82ac2534ae59e1da6ef2b555e3b219b93c3e0348c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
